blog-master/blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url,include
from blogCMS import settings
from blog import views


urlpatterns = [
    url(r'^commentTree/(?P<article_id>\d+)/',views.commentTree),
    url(r'^up_count/',views.up_count),
    url(r'^down_count/',views.down_count),
    url(r'^(?P<username>.*)/backindex/$',views.backIndex),
    url(r'^(?P<username>.*)/backindex/addarticle/$',views.addarticle),
    url(r'^(?P<username>.*)/backindex/delarticle/$',views.delarticle),
    url(r'^(?P<username>.*)/backindex/editarticle/$',views.editarticle),
    url(r'^(?P<username>.*)/com', views.com),
    url(r'^(?P<username>.*)/(?P<condition>tag|category|date)/(?P<para>.*)', views.homeSite),
    url(r'^(?P<username>.*)/article/(?P<article_id>\d+)', views.homeSite),
    url(r'^(?P<username>.*)', views.homeSite,name="blog"),



]

blog-master/blogCMS/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blogCMS import settings
from django.views.static import serve

from blog import views
from blog import urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^log_out/', views.log_out),
    url(r'^reg/', views.reg),
    url(r'^get_validCode_img/',views.get_validCode_img),

    url(r'^index/?(.*)',views.index),
    url(r'^$',views.index),
    url(r'^article/',views.article),
    url(r'^comment/',views.comment),
    url(r'^cate/(?P<site_article_category>.*)/$', views.index),

    # media配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^uploadFile/$',views.uploadFile),

    #个人站点配置
    url(r'^blog/',include("blog.urls")),
    url(r'^pc-geetest/register', views.pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^pc-geetest/ajax_validate', views.pcajax_validate, name='pcajax_validate'),



    url(r'^ajax/',views.ajax),

]

blog-master/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser       #admin 表中的有些字段就不会显示

# Create your models here.


class UserInfo(AbstractUser):  # settings:   AUTH_USER_MODEL = "blog.UserInfo"
    """
    用户信息
    """
    nid = models.BigAutoField(primary_key=True)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    telephone = models.CharField(max_length=11, blank=True, null=True,  verbose_name='手机号码')
    avatar = models.FileField(verbose_name='头像', upload_to='media/avatar', default="media/avatar/default.png",null=True,blank=True)
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user', 'follower'))
    class Meta:
        verbose_name_plural = "用户信息表"

    def __str__(self):
        return self.username            #这里可以看做是验证成功返回的值


class UserFans(models.Model):
    """
    互粉关系表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users')
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid', related_name='followers')

    class Meta:
        verbose_name_plural="互粉关系表"
        unique_together = [
            ('user', 'follower'),
        ]
    def __str__(self):
        return self.user.username



class Blog(models.Model):
    """
    站点信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32,null=True,blank=True,default="/static/theme/headle.css")
    user = models.OneToOneField(to='UserInfo', to_field='nid')
    class Meta:
        verbose_name_plural = "站点信息表"
    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')         #一个站点多个博客
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = '博客个人分类表'
        ordering = ['title']
    def __str__(self):
        return self.title




class Article(models.Model):
    '''
    文章表，最主要的一张表
    '''
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')     #外键用更加详细的描述
    read_count = models.IntegerField(default=0,verbose_name="阅读量")
    comment_count = models.IntegerField(default=0,verbose_name="评论量")
    up_count = models.IntegerField(default=0,verbose_name="推荐")
    down_count = models.IntegerField(default=0,verbose_name="踩踩")
    create_time = models.DateTimeField(verbose_name='创建时间')       # auto_now_add    当前的时间
    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True)      #多个文章对应一个类型
    user = models.ForeignKey(verbose_name='所属用户', to='UserInfo', to_field='nid')              #多个文章对应一个用户
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )
    site_article_category = models.ForeignKey(to="SiteArticleCategory", null=True,blank=True,verbose_name="小的二级分类")


    class Meta:
        verbose_name_plural = "文章表"


    def __str__(self):
        return self.title


class SiteCategory(models.Model):
    '''
    系统分类表
    '''
    name=models.CharField(max_length=32,verbose_name="系统的分类")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "系统分类表"



class SiteArticleCategory(models.Model):
    '''
    系统文章分类表
    '''
    name=models.CharField(max_length=32,verbose_name="系统分类下的分类表")
    site_category=models.ForeignKey(to="SiteCategory",blank=True,null=True,verbose_name="所属系统分类")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "系统分类分类表表"



class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField(verbose_name='文章内容', )
    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')   #每个文章的简介只是对应一片文章
    class Meta:
        verbose_name_plural = "文章详细表"
    def __str__(self):
        return self.article.title


class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    up_count = models.IntegerField(default=0)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')     #评论表是由多个人组件起来的
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')         #评论的是文章
    parent_comment = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')     #自关联，父级评论
    class Meta:
        verbose_name_plural = "评论表"
    # def __str__(self):
    #     return self.user.username


class CommentUpDown(models.Model):
    """
    评论点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)         #用户点赞
    comment = models.ForeignKey("Comment", null=True)       #对评论点赞
    state = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = "评论点赞表"
        unique_together = [('user', 'comment')]
    def __str__(self):
        return self.comment.user.username



class ArticleUpDown(models.Model):
    """
    文章点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)    #用户点赞
    article = models.ForeignKey("Article", null=True)   #文章点赞
    state = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = "文章点赞表"
        unique_together = [('user', 'article')]

    def __str__(self):
        return self.user.username


class Tag(models.Model):
    '''
    标签表
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')     #多个标签属于一个博客，，
    class Meta:
        verbose_name_plural = "标签表"
    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    '''
    文章标签的第二张表，自己新建的
    '''
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')     #对应文章
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')             #对应标签
    class Meta:
        verbose_name_plural="文章标签对应表"
        unique_together = [
            ('article', 'tag'),
        ]
    def __str__(self):
        return self.article.title+"+"+self.tag.title

blog-master/templates/addarticle.html
{% extends "backendindex.html" %}

{% block manageCon %}
    <span class="success" style="color: red"></span>

    <form action="/blog/{{ request.user.username }}/backindex/addarticle/" method="post" novalidate>
        {% csrf_token %}
        <label for="title">文章标题</label>
        <p>{{ article_form.title }}</p>
        <label for="title">文章内容</label>
        <p>{{ article_form.content }}</p>
    <p>文章分类</p>
        {% for cate in cate_list %}
            <input type="radio" name="personal_cate" value="{{ cate.nid }}">{{ cate.title }}
        {% endfor %}
    <p>文章标签</p>
        {% for tag in tag_list %}
            <input type="checkbox" name="personal_tag" value="{{ tag.nid }}">{{ tag.title }}
        {% endfor %}
    </form>
    <button id="submit">提交</button>



{% endblock %}








{% block script %}
<script>

function foo() {
    $(".success").html("")
}


    KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                        width:"800px",
                        height:"400px",
                        resizeType:0,
                        uploadJson:"/uploadFile/",
                        extraFileUploadParams:{
                           csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                       },
                });
     });
     $("#submit").click(function () {
         $.ajax({
             url:"/blog/{{ request.user.username }}/backindex/addarticle/",
             type:"POST",
             data:{
                 title:$("[name=title]").val(),
                 content:editor.html(),
                 tag:$("[name=personal_tag]").val(),
                 cate:$("[name=personal_cate]").val(),
                 csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
             },
             success:function (data) {
                 editor.html(""),
                 $("[name=title]").val(""),
                 $(".success").html("添加成功"),
                     setTimeout(foo,3000)
             }
         })
     });

    </script>
{% endblock %}

blog-master/templates/article.html
{% extends "base.html" %}

{% block left %}
    {% if request.user.is_authenticated %}
        <a href="/comment/">马上评论</a>
    {% else %}
        <a href="/login/">登录评论</a>
    {% endif %}
{% endblock %}

blog-master/templates/backendindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ request.user.username }}的后台管理首页</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/blog/manmager_page.css">
    <script src="/static/jquery/jquery-3.2.1.min.js"></script>
    <script src="/static/jquery/jquery.cookie.js"></script>

    <script src="/static/kindeditor/kindeditor-all.js"></script>
    <script src="/static/kindeditor/lang/zh-CN.js"></script>


</head>
<body>

<div class="headding">
    <div class="container"><h2>welcome<a href=""> {{ request.user.username }}</a> to myhome_page </h2></div>
</div>
<hr>

<div class="container">
    <div class="row">


        <div class="col-md-3">

            <div class="panel panel-primary">
                <div class="panel-heading"><h2>后台管理页面</h2></div>
                <div class="panel-body">
                    <h3><a href="/blog/{{ request.user.username }}/backindex/">后台管理首页</a></h3>
                    <h3><a href="/blog/{{ request.user.username }}">个人博客主页</a></h3>
                    <h3><a href="/blog/{{ request.user.username }}/backindex/">文章管理</a></h3>
                    <h3><a href="/blog/{{ request.user.username }}/backindex/tags/">标签管理</a></h3>
                    <h3><a href="/blog/{{ request.user.username }}/backindex/category/">分类管理</a></h3>
                </div>
            </div>
        </div>


        <div class="col-md-8">
            {% block manageCon %}
                <div class="panel panel-default">
                    <div class="panel-heading">用户文章信息</div>
                    <div class="panel-body">
                        <a href="/blog/{{ request.user.username }}/backindex/addarticle/">
                    <button class="btn btn-primary">+添加文章</button>
                </a>
                        <table class="table table-bordered table-hover">
                    <tr>
                        <th>编号</th>
                        <th>标题</th>
                        <th>评论数</th>
                        <th>点赞数</th>
                        <th>创建时间</th>
                        <th>编辑</th>
                        <th>删除</th>
                    </tr>
                    {% for article in article_obj %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ article.title }}</td>
                            <td>{{ article.comment_count }}</td>
                            <td>{{ article.up_count }}</td>
                            <td>{{ article.create_time }}</td>
                            <td>
                                <a href="/blog/{{ request.user.username }}/backindex/addarticle/"><button class="btn edit btn-info " article_nid="{{ article.nid }}"><span
                                        class="glyphicon glyphicon-pencil">编辑</span></button></a>
                            </td>
                            <td>
                                <button class="btn del btn-danger" article_nid="{{ article.nid }}"><span
                                        class="glyphicon glyphicon-remove">删除</span></button>
                            </td>
                        </tr>
                    {% endfor %}

                </table>
                    </div>
                </div>


                <div class="page_page" style="text-align: center">

                    {#        分页按钮功能#}
                    {% block page %}

                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if article_obj.has_previous %}
                                    <li>
                                        <a href="/blog/{{ current_user.username }}/backindex/?page={{ article_list.previous_page_number }}"
                                           aria-label="Previous">上一页</a>
                                    </li>
                                {% else %}
                                    <li class="disabled"><a href="" aria-label="Previous">上一页</a></li>
                                {% endif %}


                                {% for index in page_range %}
                                    {% if num == index %}
                                        <li class="active"><a
                                                href="/blog/{{ request.user.username }}/backindex/?page={{ index }}">{{ index }}</a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a href="/blog/{{ request.user.username }}/backindex/?page={{ index }}">{{ index }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}


                                {% if article_obj.has_next %}
                                    <li>
                                        <a href="/blog/{{ request.user.username }}/backindex/?page={{ article_list.next_page_number }}"
                                           aria-label="Previous">下一页</a></li>
                                {% else %}
                                    <li class="disabled"><a href="" aria-label="Previous">下一页</a></li>
                                {% endif %}

                            </ul>
                        </nav>

                    {% endblock %}
                </div>

            {% endblock %}

        </div>


    </div>
</div>


{% block script %}

{% endblock %}

<script>
    $(".table").on("click", ".del", function () {
        $.ajax({
            url: "/blog/{{ request.user.username }}/backindex/delarticle/",
            type: "POST",
            headers: {"X-CSRFToken": $.cookie('csrftoken')},
            data: {
                article_nid: $(this).attr("article_nid")
            },
            success: function (data) {
                var data = JSON.parse(data)
                if (data["is_del"]) {
                    location.href = "/blog/{{ request.user.username }}/backindex/"
                }
            }
        })
    });


</script>


</body>
</html>

blog-master/templates/base.html
{#<!DOCTYPE html>#}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>I'm father</title>
    <script src="/static/jquery/jquery-3.2.1.min.js"></script>
    <script src="/static/jquery/jquery.cookie.js"></script>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/js/bootstrap.min.js">
    <link rel="stylesheet" href="/static/blog/base.css">


</head>
<body>
{#网页导航首条#}
<nav class="navbar navbar-inverse navbar-fixed-top" >
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">博客园</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">当前用户{{ request.user }}</a></li>
            <li><a href="">修改密码</a></li>
            <li><a href="/log_out/">注销</a></li>
        </ul>
    </div>
</nav>

{#网页主体部分#}
<div class="container" style="margin-top: 60px">
    <div class="row">
        {#左侧菜单#}
        <div class="col-md-3">

            <ul id="main-nav" class="nav nav-tabs nav-stacked">
                <li class="active">
                    <a href="">
                        <i class="glyphicon glyphicon-home"></i>
                        首页
                    </a>
                </li>
                <li>
                    <a href="" class="nav-header collapsed" data-toggle="collapse">
                        <i class="glyphicon glyphicon-cog "></i>
                        系统管理
                    </a>

                </li>
                <li>
                    <a href="">
                        <i class="glyphicon glyphicon-user"></i>
                        用户管理
                    </a>
                </li>

                <li>
                    <a href="/article/">
                        <i class="glyphicon glyphicon-user"></i>
                        数据库
                    </a>
                </li>

                <li>
                    <a href="">
                        <i class="glyphicon glyphicon-book"></i>
                        编程语言
                    </a>
                </li>

                <li>
                    <a href="">
                        <i class="glyphicon glyphicon-tasks"></i>
                        前端设计
                    </a>
                </li>

                <li>
                    <a href="">
                        <i class="glyphicon glyphicon-fire"></i>
                        操作系统
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="glyphicon glyphicon-heart"></i>
                        收藏我
                    </a>
                </li>




            </ul>

        </div>


        {#右侧菜单#}
        <div class="col-md-9">
             {% block left %}
{#                    这里是挖的坑#}
             {% endblock %}


            {% block page %}
                这里是分页显示
            {% endblock %}

         </div>


    </div>
</div>

</body>
</html>

blog-master/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'jquery/jquery.cookie.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>


</head>
<body>

{#导航条部分#}
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home">个人博客</span></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="">当前用户<span class="glyphicon glyphicon-user"></span>：{{ request.user.username }}</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">更多操作 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/log_out/"><span class="glyphicon glyphicon-off"></span>注销</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-repeat"></span>修改密码</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-tint"></span>帮助</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-question-sign"></span>更多</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#"><span class="glyphicon glyphicon-menu-hamburger"></span>关于</a></li>
                            <li role="separator" class="divider"></li>
                        </ul>
                    </li>

                {% else %}
                    <li><a href="/login/"><span class="glyphicon glyphicon-user"></span>登录</a></li>
                    <li><a href="/reg/"><span class="glyphicon glyphicon-user"></span>注册</a></li>
                {% endif %}

            </ul>


        </div>
    </div>
</nav>



<div class="container">
    <div class="row">
        <div class="col-md-2">

            <div class="panel panel-default">
                <div class="panel-heading">网站导航分类</div>
                <div class="panel-body">
                    {% for cate in cate_list %}
                        <div class="panel panel-default">
                            <div class="panel-body cate_title">{{ cate.name }}</div>

                            <div class="panel-footer hide sub">
                                {% for sitearticlecategory in cate.sitearticlecategory_set.all %}
                                    <p><a href="/cate/{{ sitearticlecategory.name }}">{{ sitearticlecategory.name }}</a>
                                    </p>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>

        </div>


        <div class="col-md-7">

            <div class="panel panel-primary">
                <div class="panel-heading">博客园主页文章显示</div>
                <div class="panel-body">

                    {% for article in article_list %}
                        <div class="article_item">
                            <div class="title"><a href="/blog/{{ article.user.username }}/article/{{ article.nid }}"><h4>{{ article.title }}</h4></a></div>
                            <div class="row">
                                <div class="avatar col-md-2">
                                    <a href="{% url 'blog' article.user.username %}">

                                        <img src="{{ article.user.avatar.url }}" width="70" height="70" alt="">
                                    </a>
                                </div>
                                <div class="col-md-10">
                                    <p>{{ article.desc }}</p>
                                </div>
                            </div>

                            <div class="pub_info row">
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="/blog/{{ article.user.username }}">{{ article.user.username }} </a>发布于：{{ article.create_time }}
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href=""><span
                                        class="glyphicon glyphicon-comment"></span>评论{{ article.comment_count }}
                                </a>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href=""><span class="glyphicon glyphicon-thumbs-up"></span>点赞{{ article.up_count }}
                                </a>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href=""><span class="glyphicon glyphicon-share-alt">转发</span></a>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}


                </div>
            </div>

            <div class="page_page" style="text-align: center">
                {% block page %}

                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {% if article_list.has_previous %}
                                <li><a href="/index?page={{ article_list.previous_page_number }}"
                                       aria-label="Previous">上一页</a>
                                </li>
                            {% else %}
                                <li class="disabled"><a href="" aria-label="Previous">上一页</a></li>
                            {% endif %}


                            {% for index in page_range %}
                                {% if num == index %}
                                    <li class="active"><a href="/index?page={{ index }}">{{ index }}</a></li>
                                {% else %}
                                    <li><a href="/index?page={{ index }}">{{ index }}</a></li>
                                {% endif %}
                            {% endfor %}


                            {% if article_list.has_next %}
                                <li><a href="/index?page={{ article_list.next_page_number }}"
                                       aria-label="Previous">下一页</a></li>
                            {% else %}
                                <li class="disabled"><a href="" aria-label="Previous">下一页</a></li>
                            {% endif %}

                        </ul>
                    </nav>

                {% endblock %}
            </div>

        </div>


        <div class="col-md-3">
            {#            右侧分类展示#}
            <div class="panel panel-default">
                <div class="panel-heading">广告位</div>
                <div class="panel-body">
                    <p>&&&&&</p>
                    <p>$$$$$</p>
                    <p>#####</p>
                    <p>*****</p>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">备用标题二</div>
                <div class="panel-body">
                    <p>内容一</p>
                    <p>内容二</p>
                    <p>内容三</p>
                    <p>内容四</p>
                </div>
            </div>

        </div>
    </div>
</div>


<script>


    $(".cate_title").click(function () {        {#点击当前的#}
        $(".sub").addClass("hide");
        {#子菜单添加隐藏属性#}
        $(this).next().toggleClass("hide");
        {#有的话添加，没有的话去掉#}

    });


</script>

</body>
</html>

blog-master/templates/notFound.html
{#<!DOCTYPE html>#}
<html>
<head>
    <meta charset="utf-8">
    <title>Error_404_资源不存在</title>
	<style type="text/css">
	body{margin:8% auto 0;max-width: 550px; min-height: 200px;padding:10px;font-family: Verdana,Arial,Helvetica,sans-serif;font-size:14px;}p{color:#555;margin:10px 10px;}img {border:0;}.d{color:#404040;}
	</style>
</head>
<body>
<a href="http://www.cnblogs.com/"><img src="//static.cnblogs.com/images/logo_small.gif" alt="cnblogs"/></a>
<p><b>404.</b> 抱歉! 您访问的资源不存在!</p>
<p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至contact&#64;cnblogs.com与我们联系。</p>
<p><a href="/">返回网站首页</a></p>
</body>
</html>